services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
  app:
    image: 'hexagonal-architecture-app:latest'
    build:
      context: ../..
      dockerfile: docker/app/Dockerfile
    container_name: hexagonal-architecture-app
    depends_on:
      - db
    environment:
      - POSTGRES_URL=$POSTGRES_URL
      - POSTGRES_USERNAME=$POSTGRES_USERNAME
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - DEFAULT_LOGGING_LEVEL=$DEFAULT_LOGGING_LEVEL