spring:
  config:
    activate:
      on-profile: default-logging

logging:
  level:
    nl.pancompany.hexagonal.architecture.*: ${DEFAULT_LOGGING_LEVEL}

---

spring:
  config:
    activate:
      on-profile: demo-logging

logging:
  level:
    nl.pancompany.hexagonal.architecture.*: debug